name = "apigivemysolback"
main = "src/handler.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-07-12"

[observability]
enabled = true

[[kv_namespaces]]
binding = "NONCE_CACHE"
id = "093184ab07564fa589ecb60b295dd123"
